export const events: any[] = [
  // js/es
  { "date": "1995-12-04", "description": "JavaScript v1.0 was released.", "cat": "📚", "ref": "", "remark": "" },
  { "date": "1996-05-29", "description": "JScript v1.0 was released.", "cat": "📚", "ref": "", "remark": ""},
  { "date": "2009-10-28", "description": "ES5/3.1 was released.", "cat": "📚", "ref": "", "remark": ""},
  { "date": "2013-xx-xx", "description": "JSON was first standardized, as ECMA-404.", "cat": "📚", "ref": "", "remark": ""},
  { "date": "2015-06-xx", "description": "ES6(aka ES2015) was released.", "cat": "📚", "ref": "", "remark": ""},
  
  // ts
  { "date": "2012-10-xx", "description": "TypeScript v0.8 was released.", "cat": "📚", "ref": "", "remark": "" },
  { "date": "2014-04-02", "description": "TypeScript v1.0 was released.", "cat": "📚", "ref": "", "remark": "" },
  
  // node.js
  { "date": "2009-xx-xx", "description": "Node.js was created by Ryan Dahl.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2013-03-11	", "description": "Node.js v0.10 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2015-02-06", "description": "Node.js v0.12 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2015-09-08", "description": "Node.js v4.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2015-10-29", "description": "Node.js v5.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2016-04-26	", "description": "Node.js v6.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2016-10-25", "description": "Node.js v7.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2017-05-30", "description": "Node.js v8.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2017-10-01", "description": "Node.js v9.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2018-04-24", "description": "Node.js v10.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2018-10-23", "description": "Node.js v11.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2019-04-23", "description": "Node.js v12.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2019-10-22", "description": "Node.js v13.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2020-04-21", "description": "Node.js v14.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2020-10-20", "description": "Node.js v15.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2021-04-20", "description": "Node.js v16.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },

  // yui
  { "date": "2006-02-xx", "description": "YUI was released for public use.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2009-09-xx", "description": "YUI v3.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2014-08-29", "description": "it was announced that active development of YUI by Yahoo! would end.", "cat": "⚙️", "ref": "", "remark": "" },
  
  { "date": "2001-xx-xx", "description": "JSMin was created by Douglas Crockford.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2002-xx-xx", "description": "JSLint was created by Douglas Crockford.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2011-xx-xx", "description": "JSHint was created by Anton Kovalyov as a fork of the JSLint project.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2013-06-30", "description": "ESLint was created Nicholas C. Zakas.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2009-xx-xx", "description": "Closure Compiler was opened by Google. Inc.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2010-xx-xx", "description": "UglifyJS was created by Mihai Bazon.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2012-xx-xx", "description": "UglifyJS2 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2017-xx-xx", "description": "UglifyJS3 was released by Alex Lam.", "cat": "⚙️", "ref": "", "remark": "" },
  
  // package manager
  { "date": "2010-01-12", "description": "npm was created by Isaac Z. Schlueter.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2011-05-01", "description": "npm v1.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2014-09-13", "description": "npm v2.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2015-06-25", "description": "npm v3.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2016-10-21", "description": "npm v4.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2017-05-26", "description": "npm v5.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2018-05-04", "description": "npm v6.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2020-10-12", "description": "npm v7.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2016-04-18", "description": "yarn was created by facebook. Inc.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2017-09-05", "description": "yarn v1.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2019-02-19", "description": "yarn v2.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
  { "date": "2017-06-28", "description": "pnpm v1.0 was released.", "cat": "⚙️", "ref": "", "remark": "" },
]

export const packages = [
  "babel",
  "@babe/core",
  "eslint",
  "webpack",
  "parcel",
  // "mocha",
  // "tape",
  // "postcss",
  // "less",
  // "node-sass",
  // "esprima",
  // "acorn",
  // "ava",
  // "jest",
  "rollup",
  // "jscs",
  "typeScript",
  // "coffee",
  // 'bower',
]
